name: Robbie Robertson
email: rarobertsonCS@csu.fullerton.edu
github_name: rarobertsonGithub
github_link: https://github.com/rarobertsonGithub
school: California State University Fullerton
degree: Bachelors of Computer Science